routingFilm:
       resource: "@FilmothequeBundle/Resources/config/routing/routingFilm.yml"
       prefix:  /film

routingActeur:
       resource: "@FilmothequeBundle/Resources/config/routing/routingActeur.yml"
       prefix:  /
       
       