film_liste:
    pattern:  /lister
    defaults: { _controller: FilmothequeBundle:Film:lister }
    
film_ajouter:
    pattern:  /ajouter
    defaults: { _controller: FilmothequeBundle:Film:editer }

film_modifier:
    pattern:  /modifier/{id}
    defaults: { _controller: FilmothequeBundle:Film:editer }
    requirements:
        id : \d+

film_supprimer:
    pattern:  /supprimer/{id}
    defaults: { _controller: FilmothequeBundle:Film:supprimer }
    requirements:
        id : \d+
    
film_editer:
    pattern:  /editer/{id}
    defaults: { _controller: FilmothequeBundle:Film:editer }
    requirements:
        id : \d+
